# Generated by Django 4.2 on 2023-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_conversation_message_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="messeges/"),
        ),
    ]
